/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package todo;

import java.util.ArrayList;

public class Todo {
  ArrayList<String> todos = new ArrayList<String>();

  public static void main(String[] args) {}

  public ArrayList<String> addTask(String item) {
    todos.add(item);
    return todos;
  }

  public ArrayList<String> getTasks() {
    return todos;
  }
}
