/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package calculator;

public class Calculator {
  public Integer add(Integer a, Integer b) {
    Integer sum = a + b;
    return sum;
  }
  public static void main(String[] args) {
    Integer a = 2;
    Integer b = 2; 

    Calculator obj = new Calculator();

    Integer result = obj.add(a, b);
    System.out.printf("The result is %d \n", result);
  }
}
