/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package todo;

public class Todo {
  public static void main(String[] args) {
    ArrayList<String> todos = new ArrayList<String>();
  }

  public String addTask(item) {
    todos.add(item);
  }

  public String getTasks() {
    for (String i : todos) {
      System.out.println(i);
    }
  }
}
