/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pricedisplay;

public class PriceDisplay {
  public static String getPriceLabel(String item, Double price) {
    return "The price for item: " + item + " is " + price;
  }

  public static void main(String[] args) {
    System.out.println(getPriceLabel("Coffee Machine", 15.99));
  }
}
